version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
  - name: stg_orders
    columns: 
      - name: customer_id
        tests:
          - relationships:
              to: stg_customers
              field: customer_id
      - name: status
        tests: 
          - accepted_values:
              values: 
                - 'returned'
                - 'completed' 
                - 'shipped' 
                - 'placed' 
                - 'return_pending'

