version: 2

sources:
  - name: jaffle_shop
    description: A clone of a Postgres application database
    database: jaffle_shop
    tables:
      - name: customers
        description: Raw customers data
        columns: 
          - name: id
            description: Primary key for customers
            tests: 
              - unique
              - not_null
      - name: orders
        description: Raw orders data
        loaded_at_field: _ETL_LOADED_AT
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 5, period: day}
        columns: 
          - name: id
            description: Primary key for orders
            tests:
              - unique
              - not_null
      - name: payments
        description: Raw payment data
        loaded_at_field: _BATCHED_AT
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 5, period: day}
        columns:
          - name: paymentmethod
            description: Method of payment
            tests:
            - dbt_expectations.expect_column_values_to_be_in_set:
                value_set: ['credit_card','coupon','bank_transfer', 'gift_card'] 