version: 2

models:
  - name: stg_payments
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
          - relationships:
              to: stg_orders
              field: order_id 
      - name: payment_amount
        tests:
          - not_null
